version: '3.9'

services:
  postgres:
    image: postgres:15-bookworm
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root" , "-d", "blog"]
      interval: 5s
      timeout: 5s
      retries: 5  


  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_SOURCE=postgres://root:password@postgres:5432/blog?sslmode=disable

    